name: Generate CV Doc

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir output && sed -n -e '/## 経歴/,/## その他/p' ./test.txt >tmp_readme.md | sed -i -e '$d' tmp_readme.md
      - uses: docker://ghcr.io/44smkn/pandoc/ja:0.1.1
        with:
          args: tmp_readme.md --from=markdown --to=docx --reference-doc=reference.docx -o output/resume.docx
      - uses: actions/upload-artifact@main
        with:
          name: output
          path: out_put/out_resume.docx
